#!/usr/bin/env python3
"""fab_export_agent.py — generate PREVIEW fabrication output from a .dsproj.

Produces, in <project>-fab/ :
  • <name>-F_Cu.gbr … -B_Cu.gbr   Gerber RS-274X copper layers (traces + pads)
  • <name>-Edge_Cuts.gbr          board outline
  • <name>.drl                    Excellon drill (vias + through-hole pads)
  • <name>-BOM.csv                priced BOM (live ₹ from DigiKey + Mouser)
  • <name>-pick-and-place.csv     ref, x, y, rotation, side

Reads the JSON .dsproj directly (nm-free, mm units). Live pricing reuses the
vendor aggregator; if no vendor keys are set the BOM still lists parts (price ø).

This legacy exporter does not yet emit the complete mask/paste/silkscreen and
exact aperture set required for production. Its files are deliberately marked
preview-only and are rejected by the industrial release gate.

Usage:  fab_export_agent.py <project.dsproj>
"""
from __future__ import annotations
import csv
import json
import math
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # make `vendors` importable


# ── Gerber RS-274X ─────────────────────────────────────────────────────────────
def _g_coord(mm: float) -> int:
    # Gerber 4.6 format in mm → integer in units of 1e-6 mm (nm).
    return int(round(mm * 1_000_000))


def _gerber_header(layer_name: str) -> list[str]:
    return [
        "%FSLAX46Y46*%",            # 4.6 format
        "%MOMM*%",                  # millimetres
        f"G04 {layer_name} generated by DesignStudio fab export*",
        "%LPD*%",                   # layer polarity dark
    ]


def _write_gerber_layer(path: Path, layer_name: str, traces: list[dict],
                        pads: list[tuple]) -> None:
    """traces: dicts with ax/ay/bx/by/w_mm. pads: (x, y, w, h, shape).

    Every distinct trace width and pad geometry gets its own aperture;
    previously all traces on a layer were drawn with the first trace's
    width, which silently corrupted every neck-down/power segment.
    """
    lines = _gerber_header(layer_name)
    circle_ap: dict[float, int] = {}
    rect_ap: dict[tuple, int] = {}
    apdefs: list[str] = []
    next_code = 10

    def trace_aperture(width: float) -> int:
        nonlocal next_code
        key = round(width, 4)
        if key not in circle_ap:
            circle_ap[key] = next_code
            apdefs.append(f"%ADD{next_code}C,{width:.4f}*%")
            next_code += 1
        return circle_ap[key]

    # Aperture selection happens per object below; predeclare nothing here.
    for t in traces:
        trace_aperture(float(t.get("w_mm", 0.25)))
    for (_, _, w, h, shape) in pads:
        if shape == "circle" and abs(w - h) < 1e-6:
            if round(w, 4) not in circle_ap:
                circle_ap[round(w, 4)] = next_code
                apdefs.append(f"%ADD{next_code}C,{w:.4f}*%")
                next_code += 1
        else:
            key = (round(w, 4), round(h, 4))
            if key not in rect_ap:
                rect_ap[key] = next_code
                apdefs.append(f"%ADD{next_code}R,{w:.4f}X{h:.4f}*%")
                next_code += 1
    lines += apdefs

    for t in traces:
        lines.append(f"D{trace_aperture(float(t.get('w_mm', 0.25)))}*")
        lines.append(f"X{_g_coord(t['ax_mm'])}Y{_g_coord(t['ay_mm'])}D02*")  # move
        lines.append(f"X{_g_coord(t['bx_mm'])}Y{_g_coord(t['by_mm'])}D01*")  # draw
    for (x, y, w, h, shape) in pads:
        if shape == "circle" and abs(w - h) < 1e-6:
            lines.append(f"D{circle_ap[round(w, 4)]}*")
        else:
            lines.append(f"D{rect_ap[(round(w, 4), round(h, 4))]}*")
        lines.append(f"X{_g_coord(x)}Y{_g_coord(y)}D03*")                    # flash
    lines.append("M02*")
    path.write_text("\n".join(lines) + "\n")


def _write_outline(path: Path, outline_pts: list, cutouts: list) -> None:
    """Board edge from the real outline polygon plus every board cutout.

    Previously this emitted a plain rectangle: the chamfered corners and the
    four NPTH mounting cutouts were silently dropped from the preview edge.
    """
    lines = _gerber_header("Edge_Cuts")
    lines.append("%ADD10C,0.1000*%")
    lines.append("D10*")
    for polygon in [outline_pts, *[c for c in cutouts if len(c) >= 3]]:
        if len(polygon) < 3:
            continue
        lines.append(f"X{_g_coord(polygon[0][0])}Y{_g_coord(polygon[0][1])}D02*")
        for (x, y) in polygon[1:]:
            lines.append(f"X{_g_coord(x)}Y{_g_coord(y)}D01*")
        lines.append(f"X{_g_coord(polygon[0][0])}Y{_g_coord(polygon[0][1])}D01*")
    lines.append("M02*")
    path.write_text("\n".join(lines) + "\n")


def _write_excellon(path: Path, holes: list[tuple]) -> None:
    """holes: (x_mm, y_mm, dia_mm)."""
    by_dia: dict[float, list[tuple]] = {}
    for (x, y, dia) in holes:
        by_dia.setdefault(round(dia, 3), []).append((x, y))
    lines = ["M48", "METRIC,TZ"]
    tools = {}
    for i, dia in enumerate(sorted(by_dia), start=1):
        tools[dia] = i
        lines.append(f"T{i:02d}C{dia:.3f}")
    lines.append("%")
    for dia, tool in tools.items():
        lines.append(f"T{tool:02d}")
        for (x, y) in by_dia[dia]:
            lines.append(f"X{x:.3f}Y{y:.3f}")
    lines.append("T00")
    lines.append("M30")
    path.write_text("\n".join(lines) + "\n")


# ── Geometry helpers ─────────────────────────────────────────────────────────
def _pad_world(fp: dict, pad: dict) -> tuple[float, float]:
    rad = math.radians(fp.get("rot_deg", 0.0))
    px, py = pad.get("x_mm", 0.0), pad.get("y_mm", 0.0)
    wx = fp["x_mm"] + px * math.cos(rad) - py * math.sin(rad)
    wy = fp["y_mm"] + px * math.sin(rad) + py * math.cos(rad)
    return wx, wy


# ── BOM (live ₹ pricing) ───────────────────────────────────────────────────────
def _price_lookup():
    try:
        from vendors.aggregator import Aggregator
        agg = Aggregator()
        if not agg.vendors_online:
            return None
        return agg
    except Exception:
        return None


def _write_bom(path: Path, footprints: list[dict]) -> tuple[int, float]:
    # Group identical parts by lib/MPN.
    groups: dict[str, list[str]] = {}
    for fp in footprints:
        groups.setdefault(fp.get("lib", "?"), []).append(fp.get("ref", "?"))

    agg = _price_lookup()
    total = 0.0
    rows = []
    for mpn, refs in sorted(groups.items()):
        qty = len(refs)
        unit = vendor = ""
        if agg:
            try:
                best = agg.best(agg.search(mpn, limit=4))
                if best and best.price_inr:
                    unit = f"{best.price_inr:.2f}"
                    vendor = best.vendor
                    total += best.price_inr * qty
            except Exception:
                pass
        rows.append([mpn, qty, ",".join(sorted(refs)), unit, vendor])

    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["MPN", "Qty", "Refs", "Unit_INR", "Vendor"])
        w.writerows(rows)
    return len(rows), total


def _write_pnp(path: Path, footprints: list[dict]) -> None:
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["Ref", "MPN", "X_mm", "Y_mm", "Rotation", "Side"])
        for fp in footprints:
            w.writerow([fp.get("ref", "?"), fp.get("lib", ""),
                        f"{fp.get('x_mm',0):.3f}", f"{fp.get('y_mm',0):.3f}",
                        f"{fp.get('rot_deg',0):.1f}",
                        "bottom" if fp.get("side", 0) == 1 else "top"])


# ── Main ─────────────────────────────────────────────────────────────────────
def main(project: str) -> int:
    data = json.loads(Path(project).read_text())
    fps   = data.get("footprints", [])
    traces = data.get("traces", [])
    vias   = data.get("vias", [])
    bw = data.get("board_width_mm", 100.0)
    bh = data.get("board_height_mm", 80.0)
    layers = data.get("copper_layers", 2)

    stem = Path(project).stem
    out = Path(project).with_name(f"{stem}-fab")
    out.mkdir(parents=True, exist_ok=True)
    (out / "PREVIEW_ONLY.txt").write_text(
        "NOT FOR FABRICATION. Export production Gerber/ODB++ from a validated CAD backend.\n")
    print("[fab-export] PREVIEW ONLY — industrial release gate will reject these artifacts")
    print(f"[fab-export] writing to {out}/")

    # Per-layer copper Gerbers.
    layer_names = {0: "F_Cu", layers - 1: "B_Cu"}
    for li in range(layers):
        name = layer_names.get(li, f"In{li}_Cu")
        ltraces = [t for t in traces if t.get("layer", 0) == li]
        lpads = []
        for fp in fps:
            side = fp.get("side", 0)
            for pad in fp.get("pads", []):
                th = pad.get("th", False)
                on_layer = th or (side == 0 and li == 0) or (side == 1 and li == layers - 1)
                if on_layer:
                    x, y = _pad_world(fp, pad)
                    lpads.append((x, y, pad.get("w_mm", 0.6), pad.get("h_mm", 0.6),
                                  pad.get("shape", "rect")))
        _write_gerber_layer(out / f"{stem}-{name}.gbr", name, ltraces, lpads)
        print(f"[fab-export]   {name}: {len(ltraces)} traces, {len(lpads)} pads")

    _write_outline(out / f"{stem}-Edge_Cuts.gbr",
                   data.get("board_outline_pts",
                            [[0, 0], [bw, 0], [bw, bh], [0, bh]]),
                   data.get("board_cutouts", []))

    # Excellon drill: vias + through-hole pads + declared mounting holes.
    holes = [(v["x_mm"], v["y_mm"], v.get("drillMm", v.get("drill_mm", 0.3))) for v in vias]
    for fp in fps:
        for pad in fp.get("pads", []):
            if pad.get("th") and pad.get("drill_mm", 0) > 0:
                x, y = _pad_world(fp, pad)
                holes.append((x, y, pad["drill_mm"]))
    for mh in data.get("mechanical_features", {}).get("mounting_holes", []):
        if mh.get("diameter_mm", 0) > 0:
            holes.append((mh["x_mm"], mh["y_mm"], mh["diameter_mm"]))
    _write_excellon(out / f"{stem}.drl", holes)
    print(f"[fab-export]   drill: {len(holes)} holes")

    n_bom, total = _write_bom(out / f"{stem}-BOM.csv", fps)
    _write_pnp(out / f"{stem}-pick-and-place.csv", fps)
    print(f"[fab-export]   BOM: {n_bom} line items"
          + (f", est. ₹{total:.2f} total" if total else " (no live pricing)"))
    print(f"[fab-export]   pick-and-place: {len(fps)} placements")
    print(f"[fab-export] done — {bw:.1f}×{bh:.1f} mm, {layers} layers")
    return 0


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("usage: fab_export_agent.py <project.dsproj>"); sys.exit(1)
    p = sys.argv[1]
    if not os.path.exists(p):
        print(f"error: file not found: {p}"); sys.exit(1)
    sys.exit(main(p))
