using System.Globalization;
using System.IO;
using System.Text;
using DesignStudio.Model;

namespace DesignStudio.Export;

// ============================================================================
// S1/E8 — openEMS geometry export.
//
// Writes a self-contained Python script for openEMS (free FDTD,
// www.openems.de) that rebuilds one routed net in 3D: the real stackup as
// dielectric slabs (Er/tanδ from the materials library at 10 GHz), every
// trace segment as a copper box at its true layer height, vias as copper
// cylinders, and lumped ports at the net's endpoints. Running the script in
// a Python environment with openEMS installed produces full-wave
// S-parameters — sign-off-grade validation for the segments our analytic
// cascade approximates.
// ============================================================================

public static class OpenEmsExporter
{
    private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

    public static string Build(BoardDocument doc, int netId, double fMaxGHz = 20)
    {
        doc.EnsureStackup();
        var traces = doc.Traces.Where(t => !t.IsPour && t.NetId == netId).ToList();
        var vias = doc.Vias.Where(v => v.NetId == netId).ToList();
        if (traces.Count == 0)
            throw new InvalidOperationException("Net has no routed copper to export.");

        // ---- z-coordinates of every copper layer (mm, z=0 at board top) ----
        var zTop = new double[doc.CopperLayers];
        double z = 0;
        for (int i = 0; i < doc.CopperLayers; i++)
        {
            zTop[i] = z;
            z -= doc.Stackup[i].CopperThicknessMm;
            if (i + 1 < doc.CopperLayers) z -= doc.Stackup[i].DielectricHeightMm;
        }
        double zBottom = z;

        // simulation volume: net bounding box + margin
        double minX = traces.Min(t => Math.Min(t.Ax, t.Bx)) - 3;
        double maxX = traces.Max(t => Math.Max(t.Ax, t.Bx)) + 3;
        double minY = traces.Min(t => Math.Min(t.Ay, t.By)) - 3;
        double maxY = traces.Max(t => Math.Max(t.Ay, t.By)) + 3;

        string name = doc.NetName(netId).Replace('$', '_');
        var sb = new StringBuilder();
        string F(double v) => v.ToString("F4", Inv);

        sb.AppendLine("# openEMS full-wave model — generated by Design Studio");
        sb.AppendLine($"# net: {doc.NetName(netId)} · {traces.Count} segment(s), {vias.Count} via(s)");
        sb.AppendLine("# requires: python-openems, python-csxcad (https://www.openems.de)");
        sb.AppendLine("import os");
        sb.AppendLine("from CSXCAD import ContinuousStructure");
        sb.AppendLine("from openEMS import openEMS");
        sb.AppendLine("from openEMS.physical_constants import C0");
        sb.AppendLine();
        sb.AppendLine($"f_max = {F(fMaxGHz)}e9");
        sb.AppendLine("unit = 1e-3  # geometry in mm");
        sb.AppendLine();
        sb.AppendLine("FDTD = openEMS(EndCriteria=1e-4)");
        sb.AppendLine("FDTD.SetGaussExcite(f_max/2, f_max/2)");
        sb.AppendLine("FDTD.SetBoundaryCond(['PML_8']*6)");
        sb.AppendLine("CSX = ContinuousStructure()");
        sb.AppendLine("FDTD.SetCSX(CSX)");
        sb.AppendLine();

        // dielectric slabs between copper layers
        sb.AppendLine("# ---- stackup dielectrics ----");
        for (int i = 0; i + 1 < doc.CopperLayers; i++)
        {
            var l = doc.Stackup[i];
            double zHi = zTop[i] - l.CopperThicknessMm;
            double zLo = zHi - l.DielectricHeightMm;
            sb.AppendLine($"diel{i} = CSX.AddMaterial('diel{i}', epsilon={l.ErAt(10).ToString("F3", Inv)}," +
                          $" kappa={F(2 * Math.PI * 10e9 * 8.854e-12 * l.ErAt(10) * l.TanAt(10))})");
            sb.AppendLine($"diel{i}.AddBox([{F(minX)}, {F(minY)}, {F(zLo)}], [{F(maxX)}, {F(maxY)}, {F(zHi)}])");
        }
        sb.AppendLine();

        // copper traces as PEC boxes
        sb.AppendLine("# ---- net copper ----");
        sb.AppendLine("pec = CSX.AddMetal('copper')");
        int seg = 0;
        foreach (var t in traces)
        {
            double zt = zTop[t.Layer], zb = zt - doc.Stackup[t.Layer].CopperThicknessMm;
            // axis-aligned fast path; angled segments exported as thin rotated boxes via polygon
            if (Math.Abs(t.Ax - t.Bx) < 1e-9 || Math.Abs(t.Ay - t.By) < 1e-9)
            {
                double x0 = Math.Min(t.Ax, t.Bx) - (t.Ay == t.By ? 0 : t.Width / 2);
                double x1 = Math.Max(t.Ax, t.Bx) + (t.Ay == t.By ? 0 : t.Width / 2);
                double y0 = Math.Min(t.Ay, t.By) - (t.Ax == t.Bx ? 0 : t.Width / 2);
                double y1 = Math.Max(t.Ay, t.By) + (t.Ax == t.Bx ? 0 : t.Width / 2);
                if (t.Ay == t.By) { y0 = t.Ay - t.Width / 2; y1 = t.Ay + t.Width / 2; }
                if (t.Ax == t.Bx) { x0 = t.Ax - t.Width / 2; x1 = t.Ax + t.Width / 2; }
                sb.AppendLine($"pec.AddBox([{F(x0)}, {F(y0)}, {F(zb)}], [{F(x1)}, {F(y1)}, {F(zt)}])  # seg {seg}");
            }
            else
            {
                // rotated rectangle as linear polygon extruded in z
                double dx = t.Bx - t.Ax, dy = t.By - t.Ay, len = Math.Sqrt(dx * dx + dy * dy);
                double nx = -dy / len * t.Width / 2, ny = dx / len * t.Width / 2;
                sb.AppendLine($"pec.AddLinPoly([[{F(t.Ax + nx)}, {F(t.Ax - nx)}, {F(t.Bx - nx)}, {F(t.Bx + nx)}], " +
                              $"[{F(t.Ay + ny)}, {F(t.Ay - ny)}, {F(t.By - ny)}, {F(t.By + ny)}]], " +
                              $"'z', {F(zb)}, {F(zt - zb)})  # seg {seg}");
            }
            seg++;
        }
        foreach (var v in vias)
        {
            double zt = zTop[Math.Min(v.FromLayer, v.ToLayer)];
            int lo = v.BackdrillToLayer >= 0 ? v.BackdrillToLayer : Math.Max(v.FromLayer, v.ToLayer);
            double zb = zTop[lo] - doc.Stackup[lo].CopperThicknessMm;
            sb.AppendLine($"pec.AddCylinder([{F(v.X)}, {F(v.Y)}, {F(zb)}], [{F(v.X)}, {F(v.Y)}, {F(zt)}], {F(v.DiameterMm / 2)})");
        }
        sb.AppendLine();

        // reference planes (simplified: solid PEC sheets at plane layers)
        sb.AppendLine("# ---- reference planes ----");
        for (int i = 0; i < doc.CopperLayers; i++)
            if (doc.Stackup[i].Role == LayerRole.Plane)
            {
                double zt = zTop[i], zb = zt - doc.Stackup[i].CopperThicknessMm;
                sb.AppendLine($"pec.AddBox([{F(minX)}, {F(minY)}, {F(zb)}], [{F(maxX)}, {F(maxY)}, {F(zt)}])  # plane L{i + 1}");
            }
        sb.AppendLine();

        // ports at the chain endpoints (lumped, trace → nearest plane below)
        var (p1x, p1y, l1) = (traces[0].Ax, traces[0].Ay, traces[0].Layer);
        var (p2x, p2y, l2) = (traces[^1].Bx, traces[^1].By, traces[^1].Layer);
        sb.AppendLine("# ---- ports ----");
        EmitPort(sb, doc, 1, p1x, p1y, l1, zTop, F);
        EmitPort(sb, doc, 2, p2x, p2y, l2, zTop, F);
        sb.AppendLine();

        sb.AppendLine("# ---- mesh & run ----");
        sb.AppendLine("mesh = CSX.GetGrid()");
        sb.AppendLine("mesh.SetDeltaUnit(unit)");
        sb.AppendLine("res = C0/(f_max*15)/unit  # λ/15 baseline resolution");
        sb.AppendLine($"mesh.AddLine('x', [{F(minX)}, {F(maxX)}])");
        sb.AppendLine($"mesh.AddLine('y', [{F(minY)}, {F(maxY)}])");
        sb.AppendLine($"mesh.AddLine('z', [{F(zBottom - 2)}, {F(2.0)}])");
        sb.AppendLine("mesh.SmoothMeshLines('all', res, 1.4)");
        sb.AppendLine();
        sb.AppendLine($"sim_path = os.path.join(os.getcwd(), 'openems_{name}')");
        sb.AppendLine("FDTD.Run(sim_path, cleanup=True)");
        sb.AppendLine();
        sb.AppendLine("# ---- post-process to S-parameters ----");
        sb.AppendLine("import numpy as np");
        sb.AppendLine("f = np.linspace(1e6, f_max, 401)");
        sb.AppendLine("port1.CalcPort(sim_path, f); port2.CalcPort(sim_path, f)");
        sb.AppendLine("s11 = port1.uf_ref/port1.uf_inc");
        sb.AppendLine("s21 = port2.uf_ref/port1.uf_inc");
        sb.AppendLine($"np.savetxt('{name}_fullwave.csv', np.column_stack([f, abs(s11), abs(s21)])," +
                      " header='f |S11| |S21|')");
        sb.AppendLine("print('done — compare against the Design Studio .s2p export')");
        return sb.ToString();
    }

    private static void EmitPort(StringBuilder sb, BoardDocument doc, int n,
                                 double x, double y, int layer, double[] zTop, Func<double, string> F)
    {
        // port between the trace layer and the nearest plane below (or board bottom)
        double zt = zTop[layer];
        double zb = zt - 0.2;
        for (int i = layer + 1; i < doc.CopperLayers; i++)
            if (doc.Stackup[i].Role == LayerRole.Plane) { zb = zTop[i]; break; }
        sb.AppendLine($"port{n} = FDTD.AddLumpedPort({n}, 50, " +
                      $"[{F(x - 0.1)}, {F(y - 0.1)}, {F(zb)}], [{F(x + 0.1)}, {F(y + 0.1)}, {F(zt)}], " +
                      $"'z', excite={(n == 1 ? "1.0" : "0")})");
    }

    public static void Write(BoardDocument doc, int netId, string path, double fMaxGHz = 20)
        => File.WriteAllText(path, Build(doc, netId, fMaxGHz));
}
