#!/usr/bin/env python3
"""Regenerate U1's BGA power fanout vias + GND/VDD plane pours.

1. Each GND/VDD ball gets one fanout via placed in an adjacent *channel*
   (between balls) on the ball's own net, so it no longer overlaps any ball
   (eliminates the cross-net shorts and NC-ball merges).
2. The GND (layers 1,6) and VDD (layer 2) plane pours are regenerated by the
   native pour engine so they cleanly clear the repositioned vias.

Writes <proj>.regen.dsproj. Original untouched."""
import json, math, sys, ctypes as C
import drc_headless as H

NM = 1_000_000

class DcPourStroke(C.Structure):
    _fields_ = [("ax", C.c_int64), ("ay", C.c_int64), ("bx", C.c_int64),
                ("by", C.c_int64), ("width", C.c_int64)]

VIA_DIA = 0.20      # smaller via -> more channel margin (drill 0.1 -> ring 0.05)
VIA_DRILL = 0.10
POUR_W = 0.082
PLANES = [("GND", 1), ("GND", 6), ("VDD", 2)]   # net name, layer

def reposition_vias(d):
    NL = d["copper_layers"]
    id2name = {n["id"]: n["name"] for n in d["net_table"]}
    # Plane layer each power net drops to (GND uses layer 1, VDD uses layer 2).
    PLANE_LAYER = {"GND": 1, "VDD": 2}
    # Via-in-pad fanout for every GND/VDD pad on the board: a via centred on the
    # pad ties it straight down to its plane. On U1's 0.5 mm BGA a 0.2 mm via
    # clears every neighbouring ball by ~0.26 mm (> the 0.2 mm rule); elsewhere
    # the pads are isolated so clearance is ample.
    vias = []
    for fp in d["footprints"]:
        r = math.radians(fp.get("rot_deg", 0))
        side = fp.get("side", 0)
        top = 0 if side == 0 else NL - 1
        for p in fp.get("pads", []):
            nm_ = id2name.get(p.get("net", -1))
            if nm_ not in PLANE_LAYER:
                continue
            x = fp["x_mm"] + p["x_mm"]*math.cos(r) - p["y_mm"]*math.sin(r)
            y = fp["y_mm"] + p["x_mm"]*math.sin(r) + p["y_mm"]*math.cos(r)
            lo, hi = sorted((top, PLANE_LAYER[nm_]))
            vias.append({"x_mm": round(x, 4), "y_mm": round(y, 4),
                         "dia_mm": VIA_DIA, "drill_mm": VIA_DRILL,
                         "net": p.get("net"), "from": lo, "to": hi,
                         "antipad_mm": 0.0, "backdrill_to": -1, "via_type": 0})
    d["vias"] = vias
    print(f"placed {len(vias)} via-in-pad power fanout vias")
    return d

def regen_pours(d, libp):
    lib = H.load_lib(libp)
    lib.dc_pour_run.argtypes = [C.c_void_p, C.c_int32, C.c_int32] + [C.c_int64]*6
    lib.dc_pour_run.restype = C.c_int32
    lib.dc_pour_get.argtypes = [C.c_void_p, C.c_int32, C.POINTER(DcPourStroke)]
    lib.dc_pour_get.restype = C.c_int32
    nameid = {n["name"]: n["id"] for n in d["net_table"]}
    W = int(d["board_width_mm"]*NM); Hh = int(d["board_height_mm"]*NM)
    traces = []
    for (net, layer) in PLANES:
        nid = nameid[net]
        b = H.build(lib, d)        # board with current (repositioned) vias, no pour traces yet
        # clearance for this net's class
        cls = next((n["class"] for n in d["net_table"] if n["id"] == nid), 0)
        clr = next((c.get("clearance_mm", 0.2) for c in d["net_classes"] if c["id"] == cls), 0.2)
        clr += 0.012   # pour back a hair more than the DRC rule so the strict '<' boundary clears
        n = lib.dc_pour_run(b, nid, layer, int(POUR_W*NM), int(clr*NM), 0, 0, W, Hh)
        if n <= 0:
            print(f"  pour {net}@{layer}: {n} strokes"); continue
        for i in range(n):
            s = DcPourStroke()
            if lib.dc_pour_get(b, i, C.byref(s)) < 0:
                break
            traces.append({"ax_mm": s.ax/NM, "ay_mm": s.ay/NM, "bx_mm": s.bx/NM,
                           "by_mm": s.by/NM, "w_mm": s.width/NM, "net": nid,
                           "layer": layer, "pour": True})
        print(f"  pour {net}@{layer}: {n} strokes")
    d["traces"] = traces
    print(f"regenerated {len(traces)} pour strokes total")
    return d

def main():
    proj = sys.argv[1] if len(sys.argv) > 1 else "single_axis_FOC_Field_Oriented_Control_SD2.dsproj"
    libp = sys.argv[2] if len(sys.argv) > 2 else "build_linux/core/libdesigncore.so"
    relax = "--relax" in sys.argv
    d = json.load(open(proj))
    if relax:
        for c in d["net_classes"]:
            if c.get("name") in ("GND", "VDD"):
                c["clearance_mm"] = 0.1
    d = reposition_vias(d)
    d = regen_pours(d, libp)
    out = proj.replace(".dsproj", ".regen.dsproj")
    json.dump(d, open(out, "w"), separators=(",", ":"))
    print("wrote", out)

if __name__ == "__main__":
    main()
